BEGIN TRANSACTION;

CREATE TABLE STORE(
    ITEM_NO integer primary key ,
    ITEM text
    SCODE integer,
    QTY integer,
    RATE integer,
    LAST_BUY text
);

CREATE TABLE SUPPLIERS(
    SCODE integer primary key,
    SNAME text
);

INSERT INTO STORE VALUES(101, "Sharpener", 25, 60, 5, "20-Nov-20");
INSERT INTO STORE VALUES(102, "Pencil", 22, 100, 10, "14-Sep-20");
INSERT INTO STORE VALUES(103, "Eraser", 24, 30, 5, "29-Jan-19");
INSERT INTO STORE VALUES(104, "Scale 15cm", 21, 55, 15, "2-Oct-20");
INSERT INTO STORE VALUES(105, "Ballpoint Pen Blue", 23, 200, 5, "9-Jan-21");

INSERT INTO SUPPLIERS VALUES(21, "Proveedores Elegantes") ;
INSERT INTO SUPPLIERS VALUES(22, "Lime Plastics");
INSERT INTO SUPPLIERS VALUES(23, "NotWalmart Sellers");
INSERT INTO SUPPLIERS VALUES(24, "Fathom Supply");
INSERT INTO SUPPLIERS VALUES(25, "SupplyLead") ;
COMMIT;

-- PROGRAM 23 Statements

SELECT * FROM STORE ORDER BY LAST_BUY;
SELECT ITEM_NO, ITEM FROM STORE WHERE RATE > 15;
SELECT * FROM STORE WHERE (SCODE = 22 OR QTY > 110);
SELECT SCODE, MIN(RATE) FROM STORE GROUP BY SCODE;
SELECT ITEM, QTY FROM STORE S, SUPPLIERS P WHERE S.SCODE = P.SCODE AND P.SNAME = "NotWalmart Sellers";

-- Give output of following
SELECT COUNT(DISTINCT SCODE) FROM STORE;
-- OUTPUT: 5

SELECT RATE * QTY FROM STORE WHERE ITEM_NO = 104;
-- OUTPUT: 825

SELECT ITEM, SNAME FROM STORE S, SUPPLIERS P WHERE S.SCODE = P.SCODE AND ITEM_NO = 101;
-- OUTPUT: Shaxpenex/SuppLylead

SELECT MAX(LAST_BUY) FROM STORE;
-- OUTPUT: 9-Jan-21